import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Logo from "../public/stakegold_reversed.svg";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>StakeGold</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" type="image/png" href="stakegold_original.png" />
      </Head>

      <header className={styles.header}>
        <Image src={Logo} alt="logo" width="150" height="150" />
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>Coming soon!</h1>
      </main>
    </div>
  );
};

export default Home;
